AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Demonstration os AWS SAM CLI

Globals:
  Function:
    Timeout: 5

Resources:
  HelloGopher:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: ../bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: makefile